# # -- 코드를 입력하세요
# # WITH V AS (SELECT BOOK_ID, SUM(SALES) AS SALES
# # FROM BOOK_SALES
# # WHERE LEFT(SALES_DATE, 7) = '2022-01'
# # GROUP BY BOOK_ID)

# # SELECT A.author_id, A.author_name, B.category, SUM(V.SALES * PRICE) AS TOTAL_SALES
# # #SELECT *
# # FROM BOOK B
# # JOIN V ON B.BOOK_ID = V.BOOK_ID
# # JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# # GROUP BY B.author_id, category
# # ORDER BY B.author_id, category DESC

# # # SELECT 
# # #   A.AUTHOR_ID, 
# # #   B.AUTHOR_NAME, 
# # #   A.CATEGORY,
# # #   SUM(C.SALES * A.PRICE) AS TOTAL_SALES
# # # FROM 
# # #   BOOK A
# # # JOIN 
# # #   AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
# # # JOIN 
# # #   BOOK_SALES C ON C.BOOK_ID = A.BOOK_ID
# # # WHERE 
# # #   C.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# # # GROUP BY 
# # #   A.AUTHOR_ID, 
# # #   A.CATEGORY
# # # ORDER BY 
# # #   A.AUTHOR_ID ASC, 
# # #   A.CATEGORY DESC



# WITH V AS (
#     SELECT BOOK_ID, SUM(SALES) AS SUM_SALES
#     FROM BOOK_SALES
#     WHERE LEFT(SALES_DATE, 7) = '2022-01'
#     GROUP BY BOOK_ID
# )

# SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(PRICE * (SUM_SALES)) AS TOTAL_SALES
# FROM BOOK B
# JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# JOIN V ON B.BOOK_ID = V.BOOK_ID
# GROUP BY B.AUTHOR_ID, B.CATEGORY
# ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC






WITH V AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE LEFT(SALES_DATE, 7) = '2022-01'
    GROUP BY BOOK_ID
)


SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(V.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN V ON B.BOOK_ID = V.BOOK_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC











