# # -- 코드를 입력하세요
# # SELECT O.ANIMAL_ID, O.NAME
# # FROM ANIMAL_INS I
# # JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
# # ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
# # LIMIT 2;

# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_INS AS I
# JOIN ANIMAL_OUTS AS O
# ON I.ANIMAL_ID = O.ANIMAL_ID
# ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
# LIMIT 2



SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;

# SELECT I.ANIMAL_ID, I.NAME, DATEDIFF(O.DATETIME, I.DATETIME)
# FROM ANIMAL_INS I
# LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID








