# -- 코드를 입력하세요
# WITH V AS (SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE (START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'))

# SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100)) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR C 
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
# WHERE (CAR_ID not IN (SELECT * FROM V)) AND (C.CAR_TYPE IN ('세단', 'SUV')) AND (DURATION_TYPE = '30일 이상')
# GROUP BY CAR_ID
# HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

# # select *
# # from v
# # order by car_id




WITH V AS (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'))


SELECT CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE CAR_ID NOT IN (SELECT * FROM V) AND C.CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE = '30일 이상'
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, C.CAR_TYPE, CAR_ID DESC






