# -- 코드를 작성해주세요
WITH A AS (
SELECT ID,PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZEPER
FROM ECOLI_DATA)

SELECT ID, CASE WHEN SIZEPER <= 0.25 THEN 'CRITICAL' WHEN SIZEPER <= 0.50 THEN 'HIGH' WHEN SIZEPER <= 0.75 THEN 'MEDIUM' ELSE 'LOW' END AS COLONY_NAME
FROM A
ORDER BY ID









# WITH A AS (
# SELECT ID,PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS TEMP 
# FROM ECOLI_DATA)
 
    
# SELECT ID, CASE WHEN TEMP <= 0.25 THEN 'CRITICAL' WHEN TEMP <= 0.5 THEN 'HIGH' WHEN TEMP <= 0.75 THEN 'MEDIUM' ELSE 'LOW' END AS COLONY_NAME
# FROM A
# ORDER BY ID;