# -- 코드를 입력하세요
# SELECT DISTINCT U.USER_ID, U.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소', CONCAT(LEFT(TLNO, 3), '-', SUBSTRING(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS '전화번호'
# FROM USED_GOODS_USER U
# JOIN USED_GOODS_BOARD B ON B.WRITER_ID = U.USER_ID
# WHERE U.USER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(*) >= 3)
# ORDER BY U.USER_ID DESC

# #SELECT * FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(*) >= 3 ORDER BY WRITER_ID
# #SELECT * FROM USED_GOODS_BOARD



WITH V AS (
    SELECT WRITER_ID AS USER_ID
    FROM USED_GOODS_BOARD
    GROUP BY USER_ID
    HAVING COUNT(*) >= 3
)

SELECT U.USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, CONCAT(LEFT(TLNO, 3), '-', SUBSTRING(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER U
JOIN V ON U.USER_ID = V.USER_ID
ORDER BY U.USER_ID DESC




