# SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
# FROM ANIMAL_OUTS O
# JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
# WHERE I.ANIMAL_ID NOT IN (
#     SELECT ANIMAL_ID
#     FROM ANIMAL_INS
#     WHERE (SEX_UPON_INTAKE LIKE 'Spayed%') OR (SEX_UPON_INTAKE LIKE 'Neutered%')
# ) AND ((SEX_UPON_OUTCOME LIKE 'Spayed%') OR (SEX_UPON_OUTCOME LIKE 'Neutered%'))
# ORDER BY O.ANIMAL_ID


SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IN (SELECT ANIMAL_ID FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE 'Intact%') AND O.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS WHERE SEX_UPON_OUTCOME LIKE 'Intact%')
ORDER BY O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME










