-- 코드를 작성해주세요
WITH V AS(
SELECT FISH_TYPE, COUNT(*) AS COUNTED
FROM FISH_INFO
GROUP BY FISH_TYPE)

SELECT V.COUNTED AS FISH_COUNT, F.FISH_NAME
FROM FISH_NAME_INFO F
RIGHT JOIN V ON F.FISH_TYPE = V.FISH_TYPE
ORDER BY V.COUNTED DESC