# # -- 코드를 입력하세요
WITH V AS (SELECT USER_ID
FROM USER_INFO
WHERE YEAR(JOINED) = '2021')

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM V), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN V ON O.USER_ID = V.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH







# WITH V AS (
#     SELECT USER_ID
#     FROM USER_INFO
#     WHERE YEAR(JOINED) = '2021'
# )
# # WITH V AS (SELECT USER_ID
# # FROM USER_INFO
# # WHERE YEAR(JOINED) = '2021')

# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM V), 1) AS PUCHASED_RATIO
# FROM ONLINE_SALE O
# JOIN V ON O.USER_ID = V.USER_ID
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH



# WITH V AS (SELECT ONLINE_SALE_ID, U.USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
# FROM USER_INFO U
# JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
# WHERE YEAR(U.JOINED) = 2021)

# SELECT YAER(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM V), 1) AS PUCHASED_RATIO
# FROM V











