-- 코드를 작성해주세요

WITH RECURSIVE V AS(
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, 1 + V.GEN AS GEN
    FROM ECOLI_DATA E
    JOIN V ON E.PARENT_ID = V.ID
)

SELECT COUNT(*) AS COUNT, GEN AS GENERATION
FROM V
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GEN