# -- 코드를 입력하세요
# WITH V AS (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
# FROM FOOD_ORDER
# WHERE LEFT(PRODUCE_DATE, 7) = '2022-05'
# GROUP BY PRODUCT_ID)

# SELECT F.PRODUCT_ID, PRODUCT_NAME, (AMOUNT * PRICE) AS TOTAL_SALES
# FROM FOOD_PRODUCT F
# JOIN V ON F.PRODUCT_ID = V.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID



SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (SUM(O.AMOUNT) * P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE LEFT(O.PRODUCE_DATE, 7) = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC










