# -- 코드를 입력하세요
# WITH V AS (SELECT HISTORY_ID, CAR_ID, (DATEDIFF(END_DATE, START_DATE) + 1) AS DATE, CASE WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상' WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 THEN '30일 이상' WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 THEN '7일 이상' ELSE NULL END AS DURATION_TYPE
#            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)


# SELECT HISTORY_ID, CASE WHEN V.DURATION_TYPE IS NULL THEN (daily_fee * V.DATE) ELSE ROUND(DAILY_FEE * V.DATE * (1 - discount_rate / 100)) END AS FEE
# FROM V
# JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = V.CAR_ID
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON c.car_type = p.car_type AND V.DURATION_TYPE = P.DURATION_TYPE
# WHERE C.CAR_TYPE = '트럭' 
# ORDER BY FEE DESC, HISTORY_ID DESC



WITH V AS (
    SELECT HISTORY_ID, C.CAR_ID, CAR_TYPE, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS DATE, CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상' WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상' WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상' ELSE NULL END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, CASE WHEN V.DURATION_TYPE IS NULL THEN (daily_fee * V.DATE) ELSE ROUND(DAILY_FEE * V.DATE * (1 - discount_rate / 100)) END AS FEE
FROM V
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON V.car_type = P.car_type AND V.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC










