# # # -- 코드를 입력하세요
# # SELECT U.USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
# # FROM USED_GOODS_USER U
# # JOIN USED_GOODS_BOARD B ON B.WRITER_ID = U.USER_ID
# # WHERE STATUS = 'DONE' 
# # GROUP BY WRITER_ID 
# # HAVING SUM(PRICE) >= 700000
# # ORDER BY TOTAL_SALES

# # # SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING SUM(PRICE) >= 700000



# WITH V AS (
#     SELECT WRITER_ID AS USER_ID, SUM(PRICE) AS SUM_PRICE
#     FROM USED_GOODS_BOARD
#     WHERE STATUS = "DONE"
#     GROUP BY USER_ID
# )

# SELECT U.USER_ID, U.NICKNAME, V.SUM_PRICE
# FROM USED_GOODS_USER U
# JOIN V ON U.USER_ID = V.USER_ID
# WHERE V.SUM_PRICE >= 700000
# ORDER BY V.SUM_PRICE







WITH V AS (
    SELECT WRITER_ID AS USER_ID, SUM(PRICE) AS SUM_PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY USER_ID
)



SELECT U.USER_ID, U.NICKNAME, V.SUM_PRICE AS TOTAL_SALES
FROM V
JOIN USED_GOODS_USER U ON V.USER_ID = U.USER_ID
WHERE V.SUM_PRICE >= 700000
GROUP BY U.USER_ID
ORDER BY TOTAL_SALES;






