-- 코드를 작성해주세요
WITH V AS (
    SELECT EMP_NO, CASE WHEN AVG(SCORE) >= 96 THEN 'S' WHEN AVG(SCORE) >= 90 THEN 'A' WHEN AVG(SCORE) >= 80 THEN 'B' ELSE 'C' END AS GRADE, CASE WHEN AVG(SCORE) >= 96 THEN 0.2 WHEN AVG(SCORE) >= 90 THEN 0.15 WHEN AVG(SCORE) >= 80 THEN 0.1 ELSE 0 END AS BONUS
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT H.EMP_NO, H.EMP_NAME, V.GRADE, (H.SAL * V.BONUS) AS BONUS
FROM HR_EMPLOYEES H
JOIN V ON H.EMP_NO = V.EMP_NO
ORDER BY H.EMP_NO