# # SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
# # FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# # WHERE CAR_ID IN (SELECT CAR_ID
# # FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# # WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
# # GROUP BY CAR_ID
# # HAVING COUNT(*) >= 5) AND (START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31')
# # GROUP BY MONTH, CAR_ID
# # ORDER BY MONTH, CAR_ID DESC









# WITH V AS (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE MONTH(START_DATE) BETWEEN 8 AND 10
#     GROUP BY CAR_ID
#     HAVING COUNT(*) >= 5
# )

# SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
# JOIN V ON C.CAR_ID = V.CAR_ID
# WHERE MONTH(C.START_DATE) BETWEEN 8 AND 10
# GROUP BY MONTH, CAR_ID
# ORDER BY MONTH, CAR_ID DESC






WITH V AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT * FROM V) AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY CAR_ID, MONTH
ORDER BY MONTH, CAR_ID DESC






