-- 코드를 작성해주세요
WITH V AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXP
FROM ECOLI_DATA
GROUP BY YEAR)

SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, (V.MAXP - D.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA D
JOIN V ON YEAR(D.DIFFERENTIATION_DATE) = V.YEAR
ORDER BY YEAR, YEAR_DEV
