-- 코드를 작성해주세요
WITH V AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT F.ID, I.FISH_NAME, F.LENGTH
FROM FISH_INFO F
INNER JOIN FISH_NAME_INFO I ON F.FISH_TYPE = I.FISH_TYPE
WHERE (F.FISH_TYPE, F.LENGTH) IN (SELECT * FROM V)
ORDER BY F.ID