WITH V AS(
SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_EMPLOYEES
GROUP BY DEPT_ID)

SELECT H.DEPT_ID, H.DEPT_NAME_EN, V.AVG_SAL
FROM HR_DEPARTMENT H
JOIN V ON H.DEPT_ID = V.DEPT_ID
ORDER BY V.AVG_SAL DESC