# -- 코드를 작성해주세요
# WITH V AS (
# SELECT FISH_TYPE
# FROM FISH_INFO
# GROUP BY FISH_TYPE
# HAVING AVG(IFNULL(LENGTH, 10)) >= 33)

# # SELECT *
# # FROM V

# SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
# FROM FISH_INFO
# WHERE FISH_TYPE IN (SELECT * FROM V)
# GROUP BY FISH_TYPE
# ORDER BY FISH_TYPE







WITH A AS (SELECT FISH_TYPE
           FROM FISH_INFO
           GROUP BY FISH_TYPE
           HAVING AVG(IFNULL(LENGTH, 10)) >= 33)

SELECT COUNT(*) AS FISH_COUNT, MAX(F.LENGTH) AS MAX_LENGTH, A.FISH_TYPE
FROM FISH_INFO F
JOIN A ON F.FISH_TYPE = A.FISH_TYPE
GROUP BY A.FISH_TYPE
ORDER BY A.FISH_TYPE;






